import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

const TokenInput = z.object({
  token: z.string().min(8).max(64).regex(/^[A-Za-z0-9_-]+$/),
  force: z.boolean().optional(),
});

function calcTotal(items: any[], taxPct: number) {
  const subtotal = (items ?? []).reduce(
    (s, it) => s + (Number(it?.qty) || 0) * (Number(it?.price) || 0),
    0,
  );
  const tax = subtotal * ((Number(taxPct) || 0) / 100);
  return { subtotal, tax, total: subtotal + tax };
}

function normalizeExpiresAtMs(v: unknown): number | null {
  if (v == null) return null;
  const n = Number(v);
  if (!isFinite(n) || n <= 0) return null;
  return n < 1e11 ? n * 1000 : n;
}

async function loadByToken(token: string) {
  const { data, error } = await supabaseAdmin
    .from("invoices")
    .select("id, user_id, number, client_snapshot, items, currency, tax, memo, status, issue_date, due_date, payment_request, payment_hash, satoshis, expires_at, verify_url, paid_at, pay_token, activity")
    .eq("pay_token", token)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Invoice not found");
  return data as any;
}

async function loadOwnerProfile(userId: string) {
  const { data, error } = await supabaseAdmin
    .from("profiles")
    .select("business_name, logo_url")
    .eq("id", userId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data as any;
}

function publicInvoice(row: any, profile: any) {
  const { total } = calcTotal(row.items ?? [], row.tax ?? 0);
  return {
    number: row.number as string,
    currency: row.currency as "USD" | "BTC",
    total,
    clientName: (row.client_snapshot?.name as string) ?? "",
    dueDate: row.due_date as string | null,
    status: row.status as "draft" | "pending" | "paid",
    memo: (row.memo as string) ?? "",
    paymentRequest: row.payment_request as string | null,
    paymentHash: row.payment_hash as string | null,
    satoshis: row.satoshis != null ? Number(row.satoshis) : null,
    expiresAt: normalizeExpiresAtMs(row.expires_at),
    verifyUrl: (row.verify_url as string | null) ?? null,
    paidAt: row.paid_at as string | null,
    businessName: (profile?.business_name as string) || "BlinkInvoice",
    logoUrl: (profile?.logo_url as string) || null,
  };
}

export const getPayInfo = createServerFn({ method: "POST" })
  .inputValidator((d) => TokenInput.parse(d))
  .handler(async ({ data }) => {
    const row = await loadByToken(data.token);
    const profile = await loadOwnerProfile(row.user_id);
    return publicInvoice(row, profile);
  });

// Lightning invoices are now pre-generated by the merchant via their
// connected wallet. The pay page just returns whatever is on the row;
// it never mints a new BOLT11 from the server.
export const refreshPayInvoice = createServerFn({ method: "POST" })
  .inputValidator((d) => TokenInput.parse(d))
  .handler(async ({ data }) => {
    const row = await loadByToken(data.token);
    const profile = await loadOwnerProfile(row.user_id);
    return publicInvoice(row, profile);
  });

// Status check: if a verify URL is stored (LNURL/Lightning Address),
// poll it directly. Otherwise just return the current DB status.
export const checkPayStatus = createServerFn({ method: "POST" })
  .inputValidator((d) => TokenInput.parse(d))
  .handler(async ({ data }) => {
    const row = await loadByToken(data.token);
    if (row.status === "paid") return { status: "paid" as const };
    const verifyUrl = row.verify_url as string | undefined;
    if (!verifyUrl) return { status: "pending" as const };

    try {
      const res = await fetch(verifyUrl);
      if (!res.ok) return { status: "pending" as const };
      const j: any = await res.json();
      const settled = j?.settled === true || j?.status === "OK" && j?.settled !== false;
      if (settled) {
        const activity = Array.isArray(row.activity) ? row.activity : [];
        await supabaseAdmin
          .from("invoices")
          .update({
            status: "paid",
            paid_at: new Date().toISOString(),
            activity: [...activity, { at: new Date().toISOString(), text: "Payment received via Lightning" }],
          })
          .eq("id", row.id);
        return { status: "paid" as const };
      }
    } catch {
      // ignore transient
    }
    return { status: "pending" as const };
  });
